# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven in Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workdir: attsw-silva
    strategy:
        matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
          include:
            - java: 8
              additional-maven-args: >
                -Pcoveralls
                -DrepoToken=$COVERALLS_REPO_TOKEN
                -DpullRequest=${{ github.event.pull_request.number }}
            - java: 11
    
    name: Build with Java on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
            restore-keys: ${{ runner.os }}-m2-
            
    - name: Build with Maven
      #run: mvn -f ./attsw-silva/pom.xml clean verify
      run: >
        xvfb-run mvn verify ${{ matrix.additional-maven-args }}
      working-directory: ${{ env.workdir }}
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Generate JUnit Report
      run: >
        mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive JUnit Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: surefire-report-jdk-${{ matrix.java }}
        path: '**/target/site'
    - name: Build with Maven and SonarCloud
      run: >
        xvfb-run mvn verify -Pjacoco sonar:sonar
        -Dsonar.organization=hondamunigeprasannasilva
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.projectKey=HondamunigePrasannaSilva_StudyPlanManger-Attsw
      working-directory: ${{ env.workdir }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

